```{r solution, echo = FALSE, eval= FALSE, results = "hide"}
library(simfinapi)
library(dplyr)
library(readr)

# set api key - make sure you got your own at https://simfin.com/data/access/api
#my_api_key <- read_lines('~/GDrive/98-pass-and-bash/.api_key_simfin.txt')
my_api_key <- ''

cache_dir <- fs::path_temp("cache-simfin")
fs::dir_create(cache_dir)

# get info
simfinapi::sfa_set_api_key(my_api_key)
simfinapi::sfa_set_cache_dir(cache_dir)

# get info
df_info_companies <- simfinapi::sfa_get_entities()

# check it
glimpse(df_info_companies)

n_companies <- n_distinct(df_info_companies$ticker)

my_sol <- n_companies
```

```{r datageneration, echo = FALSE, results = "hide"}
#my_answers <- afedR3::make_random_answers(my_sol)
```

Question
========

Use function `simfinapi::sfa_get_entities()` to import data about all available companies in [Simfin](https://simfin.com). How many companies do you find?  (see function `dplyr::n_distinct()`). 

```{r questionlist, echo = FALSE, results = "asis"}
#exams::answerlist(my_answers, markup = "markdown")
```

Solution
================

```{r solution, eval=FALSE}
```


Meta-information
================
extype: string
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: "simfinr 01"
exshuffle: TRUE

