```{r solution, echo = FALSE, results = "hide", message=FALSE}
ticker <- '^GSPC'
first_date <- '1950-01-01'
last_date <- '2021-01-01'

df_sp500 <- yfR::yf_get('^GSPC', 
                            first_date,
                            last_date)

select_n <- 5
tab <- dplyr::tibble(position = 1:select_n,
              top5_positive = sort(df_sp500$ret_adjusted_prices, 
                                   decreasing = TRUE)[1:select_n],
              top5_negative = sort(df_sp500$ret_adjusted_prices, 
                                   decreasing = FALSE)[1:select_n])

print(tab)

my_sol <- sum(tab$top5_positive)
```

```{r datageneration, echo = FALSE, results = "hide"}
# none
my_answers <- afedR3::make_random_answers(my_sol)
```

Question
========

Use the `yfR` package to download the SP500 index data (`'^GSPC'`) from `r first_date` to `r last_date`. What is the sum of the `r select_n` highest positive returns on the index?

```{r questionlist, echo = FALSE, results = "asis"}
exams::answerlist(my_answers, markup = "markdown")
```

Solution
================

```{r solution, eval=FALSE}
```


Meta-information
================
extype: schoice
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: "yfr "
exshuffle: TRUE

