```{r solution, echo = FALSE, results = "hide", message=FALSE, eval=TRUE}
set.seed(5)

# number of obs
n_row <- 100

# set x as Normal (0, 1)
x <- rnorm(n_row)

# set coefficients
my_alpha <- 1.5
my_beta <- 0.5

# build y
y <- my_alpha + my_beta*x + rnorm(n_row)

my_lm <- lm(formula = y ~ x, data = tibble::tibble(x, y))

summary(my_lm)

library(car)

# set test matrix
test_matrix <- matrix(c(my_alpha,  # alpha test value
                        my_beta))  # beta test value

# hypothesis matrix 
hyp_mat <- matrix(c(1.5, 0,
                    0  , 0.5),
                  nrow = 2)

# do test
my_waldtest <- linearHypothesis(my_lm, 
                                hypothesis.matrix = hyp_mat, 
                                rhs = test_matrix)

# print result
my_sol <- my_waldtest$F[2]
```

```{r datageneration, echo = FALSE, results = "hide"}
# none
my_answers <- afedR3::make_random_answers(my_sol)
```

Question
========

Using the `r afedR3::format_pkg_text("car")` package, test the joint hypothesis that the value of alpha is equal to `r my_alpha` and the value of beta is equal to `r my_beta`. What is the value of the resulting F test?

```{r questionlist, echo = FALSE, results = "asis"}
exams::answerlist(my_answers, markup = "markdown")
```

Solution
================

```{r solution, eval=FALSE}
```


Meta-information
================
extype: schoice
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: "function 01"
exshuffle: TRUE

