```{r solution, echo = FALSE, results = "hide", message=FALSE, eval=FALSE}
library(dplyr)

tickers <- yfR::yf_index_composition("DOW")$ticker
first_date <- Sys.Date() - 3*365
last_date  <- Sys.Date()

df_stocks <- yfR::yf_get(tickers, 
                         first_date, 
                         last_date)

library(fMarkovSwitching)

set.seed(10)

random_stocks <- sample(unique(df_stocks$ticker), 4)

temp_df <- df_stocks |>
  filter(ticker %in% random_stocks)

tab_switching_model <- temp_df |>
  na.omit() |>
  group_by(ticker) |>
  do(ms_model = MS_Regress_Fit(
        dep = .$ret_adjusted_prices,
        indep = rep(1, nrow(.)),
        S = c(1), 
        k = 2))

glimpse(tab_switching_model[[2]])
```

```{r datageneration, echo = FALSE, results = "hide"}
# none
#my_answers <- afedR3::make_random_answers(my_sol)
my_answers <- rep(NA, 5)
```

Question
========

For the same SP500 database, select 4 stocks at random and estimate a Markov regime switching model with a constant and two states. Compare the estimated parameters across the models. Are they similar? 


Solution
================

```{r solution, eval=FALSE}
```


Meta-information
================
extype: string
exsolution: `r mchoice2string(c(TRUE, FALSE, FALSE, FALSE, FALSE), single = TRUE)`
exname: "ms models"
exshuffle: TRUE

